# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Dot product in RcppArmadillo.
#'
#' @param x1 numeric vector
#' @param x2 numeric vector
#' @return dot product, that is \code{t(x1)%*%x2}
dotArma <- function(x1, x2) {
    .Call(`_mypack_dotArma_I`, x1, x2)
}

rcpp_hello_world <- function() {
    .Call(`_mypack_rcpp_hello_world`)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_mypack_RcppExport_registerCCallable', PACKAGE = 'mypack')
})
