# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_secondPack_rcpp_hello_world`)
}

secondDot <- function(x1, x2) {
    .Call(`_secondPack_secondDot_I`, x1, x2)
}

