// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// dotArma_I
arma::vec dotArma_I(arma::vec x1, arma::vec x2);
RcppExport SEXP _mypack_dotArma_I(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(dotArma_I(x1, x2));
    return rcpp_result_gen;
END_RCPP
}
// dotArma_I2
arma::vec dotArma_I2(arma::vec x1, arma::vec x2);
static SEXP _mypack_dotArma_I2_try(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(dotArma_I2(x1, x2));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _mypack_dotArma_I2(SEXP x1SEXP, SEXP x2SEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_mypack_dotArma_I2_try(x1SEXP, x2SEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _mypack_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _mypack_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("arma::vec(*dotArma2)(arma::vec,arma::vec)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _mypack_RcppExport_registerCCallable() { 
    R_RegisterCCallable("mypack", "_mypack_dotArma2", (DL_FUNC)_mypack_dotArma_I2_try);
    R_RegisterCCallable("mypack", "_mypack_RcppExport_validate", (DL_FUNC)_mypack_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_mypack_dotArma_I", (DL_FUNC) &_mypack_dotArma_I, 2},
    {"_mypack_dotArma_I2", (DL_FUNC) &_mypack_dotArma_I2, 2},
    {"_mypack_rcpp_hello_world", (DL_FUNC) &_mypack_rcpp_hello_world, 0},
    {"_mypack_RcppExport_registerCCallable", (DL_FUNC) &_mypack_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mypack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
