on:
  push:
    branches:
      - main
      - master

name: build

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew install --cask xquartz

      - name: Install dependencies
        run: R -e 'install.packages(c(
          "blogdown",
          "tidyverse", 
          "mgcViz", 
          "devtools", 
          "microbenchmark",
          "gamair",
          "tweedie",
          "Rcpp",
          "RcppArmadillo",
          "RcppParallel",
          "BH",
          "mvtnorm",
          "hexbin",
          "sitmo",
          "RhpcBLASctl"
          ))'

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo()'

      - name: Build site
        run: |
          R -e 'blogdown::build_site(build_rmd = TRUE)'
          rm public/.gitignore

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
